[package]
name = "mincaml"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[[bin]]
name = "mc"
path = "src/main.rs"

[dependencies]
cranelift-codegen = "0.63"
cranelift-frontend = "0.63"
cranelift-module = "0.63"
cranelift-native = "0.63"
cranelift-object = "0.63"
fxhash = "0.2.1"

[profile.release]
lto = true
