[package]
name = "mincaml"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[[bin]]
name = "mc"
path = "src/main.rs"

[dependencies]
pretty = "0.10"
rustyline = "6.0"

[profile.release]
lto = true
