[package]
name = "mincaml"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[[bin]]
name = "mc"
path = "src/main.rs"

[dependencies]
fxhash = "0.2.1"
rustyline = "6.0"
take_mut = "0.2.2"

[profile.release]
lto = true
